# Generated by Django 3.1.4 on 2020-12-21 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='age',
            new_name='born_date',
        ),
    ]
